TripApp/TripApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('users/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

TripApp/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.home, name='home'),
    path('posts/', views.posts_list, name='posts_list'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/create/', views.create_post, name='create_post'),
    path('posts/<int:post_id>/update/', views.update_post, name='update_post'),
    path('posts/<int:post_id>/delete/', views.delete_post, name='delete_post'),
    path('posts/tags/<slug:slug>/', views.tagged_posts, name='tagged_posts'),
    path('posts/tags/', views.popular_tag_list, name='tag_list'),
    path('like/<int:post_id>/', views.post_like, name='post_like'),
    path('posts/comments/<int:comment_id>/update/', views.update_comment, name='update_comment'),
    path('posts/comments/<int:comment_id>/delete/', views.delete_comment, name='delete_comment'),
    path('posts/locations/', views.popular_location_list, name='location_list'),
]

TripApp/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('list/', views.users_list, name='users_list'),
    path('detail/<int:user_id>/', views.user_detail, name='user_detail'),
    path('edit/<int:user_id>', views.edit_profile, name='edit_user'),
    path('delete/<int:user_id>/', views.delete_profile, name='delete_user'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
]

TripApp/users/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse

from PIL import Image

from .managers import ProfileManager


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='users/%Y/%m/%d', blank=True, null=True)
    bio = models.TextField(max_length=500)
    location = models.CharField(max_length=50)
    # Default Manager
    objects = models.Manager()
    # Custom Manager
    profiles = ProfileManager()

    def __str__(self):
        return f'Profile for user {self.user.username}'

    def get_absolute_url(self):
        return reverse('users:user_detail', args=[self.user.pk])

    @property
    def image_url(self):
        if self.image:
            return self.image.url
        return '#'

    @property
    def get_posts_count(self):
        return self.user.posts.all().count()

    @property
    def get_total_likes_count(self):
        likes_count = 0
        user_posts = self.user.posts.all()

        for post in user_posts:
            likes_count += post.likes.count()

        return likes_count

    def save(self, *args, **kwargs):
        """ Resizing an image """
        super(Profile, self).save(*args, **kwargs)

        if self.image:
            img = Image.open(self.image.path)

            if img.height > 300 or img.width > 300:
                output_size = (300, 300)
                img.thumbnail(output_size)
                img.save(self.image.path)

    class Meta:
        verbose_name = 'profile'
        verbose_name_plural = 'profiles'


TripApp/users/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Profile


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'email')


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('image', 'bio', 'location')

TripApp/users/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.contrib.auth.models import User, auth
from django.contrib.auth import authenticate
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import Profile
from .forms import UserEditForm, ProfileEditForm
from posts.models import Post


def register(request):
    if request.method == 'POST':
        first_name = request.POST.get('firstName', False)
        username = request.POST.get('username', False)
        email = request.POST.get('email', False)
        password = request.POST.get('password',False)
        password2 = request.POST.get('password2', False)

        if password == password2:
            if User.objects.filter(username=username).exists():
                messages.info(request, 'Please use another username')
                return redirect('users:register')
            else:
                user = User.objects.create_user(first_name=first_name, username=username,
                                                password=password, email=email)
                user.save()
                # Create profile for new user
                Profile.objects.create(user=user)
                messages.success(request, 'Your account has been created!')
                return redirect('users:login')
        else:
            messages.info(request, 'Password didn\'t match')
            return redirect('users:register')
    else:
        return render(request, 'users/registration/register.html')


def login(request):
    if request.method == 'POST':
        username = request.POST.get('username', False)
        password = request.POST.get('password', False)

        user = authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return redirect('posts:posts_list')
        else:
            messages.info(request, 'Invalid credentials')
            return redirect('users:login')
    else:
        return render(request, 'users/registration/login.html')


def logout(request):
    auth.logout(request)
    return render(request, 'users/registration/logged-out.html')


@login_required
def user_detail(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    posts = Post.objects.filter(user=user).order_by('-created')
    posts_count = user.profile.get_posts_count
    user_likes_count = user.profile.get_total_likes_count
    return render(request, 'users/user_detail.html', {'user': user,
                                                      'posts': posts,
                                                      'posts_count': posts_count,
                                                      'likes_count': user_likes_count})


@login_required
def users_list(request):
    current_user = request.user
    users_list = User.objects.all().exclude(id=current_user.id).order_by('-date_joined')
    users = None
    paginator = Paginator(users_list, 5)
    page = request.GET.get('page')

    try:
        users = paginator.page(page)
    except PageNotAnInteger:
        users = paginator.page(1)
    except EmptyPage:
        users = paginator.page(paginator.num_pages)
    return render(request, 'users/users_list.html', {'page': page, 'users': users})


@login_required
def edit_profile(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    profile = get_object_or_404(Profile, user=user)
    if request.user != user:
        raise PermissionDenied
    else:
        if request.method == 'POST':
            user_form = UserEditForm(data=request.POST, files=request.FILES, instance=user)
            profile_form = ProfileEditForm(data=request.POST, files=request.FILES, instance=user.profile)

            if user_form.is_valid() and profile_form.is_valid():
                user.first_name = user_form.cleaned_data.get('first_name', False)
                user.email = user_form.cleaned_data.get('email', False)
                profile.bio = profile_form.cleaned_data.get('bio', False)
                profile.location = profile_form.cleaned_data.get('location', False)
                profile.image = profile_form.cleaned_data.get('image', False)

                user.save()
                profile.save()

                messages.success(request, 'Your account has been updated')
                return redirect(reverse('users:user_detail', kwargs={'user_id': user_id}))
        else:
            user_form = UserEditForm(instance=user)
            profile_form = ProfileEditForm(instance=user.profile)

    return render(request, 'users/edit_profile.html', {'user_form': user_form,
                                                       'profile_form': profile_form})


@login_required
def delete_profile(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    if request.user != user:
        raise PermissionDenied
    else:
        if request.method == 'POST':
            user.delete()
            messages.success(request, 'Your account has been deleted')
            return redirect('posts:home')
    return render(request, 'users/confirm_delete_user.html')

TripApp/users/templates/users/edit_profile.html
{% extends "posts/base.html" %}
{% load static %}
{% block stylesheet %}
    <link rel="stylesheet" href="{% static "css/post_create_style.css" %}">
{% endblock %}

{% block title %}Create Post{% endblock %}

{% block content %}
    <div class="container">
        <form id="post-form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_first_name">First Name</label>
                <input type="text" name="first_name" required id="id_first_name" value="{{ user.first_name }}">
            </div>
            <div class="form-group">
                <label for="id_email">Email</label>
                <input type="email" name="email" required id="id_email" value="{{ user.email }}">
            </div>
            <div class="form-group">
                <label for="id_location">Location</label>
                <input type="text" name="location" required id="id_location" value="{{ user.profile.location }}">
            </div>
            <div class="form-group">
                <label for="id_bio">Bio</label>
                <textarea name="bio" required id="id_bio">{{ user.profile.bio }}</textarea>
            </div>
            <div class="form-group last">
                <img src="{{ request.user.profile.image_url }}" alt="image" width="100" height="100">
                <div class="image-input">
                    <label for="id_image">Profile Image</label>
                    <input type="file" name="image" accept="image/*" id="id_image" value="{{ user.profile.image_url }}">
                </div>
            </div>
            <button type="submit">Save</button>
        </form>
    </div>
{% endblock %}




TripApp/users/templates/users/reigstration_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/9fada548c3.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="./register_style.css">
    {% block stylesheet %}
    {% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header>
        <nav id="navbar">
            <div class="header-container">
                <h1 class="logo"><a href="{% url "posts:home" %}"><i class="fas fa-camera-retro fa-2x"></i><span class="logo-text">Trip</span>App</a></h1>
                <ul>
                    <li><a href="{% url "users:login" %}"><i class="fas fa-sign-in-alt fa-2x"></i>Sign In</a></li>
                    <li><a href="{% url "users:register" %}"><i class="fas fa-user-plus fa-2x"></i>Sign Up</a></li>
                </ul>
            </div>
        </nav>
    </header>
    {% block content %}
    {% endblock %}
    <footer>
        <p>TripApp &copy; 2020, All Rights Reserved</p>
    </footer>

</body>
</html>

TripApp/users/templates/users/user_detail.html
{% extends "posts/base.html" %}
{% load static %}
{% block stylesheet %}
    <link rel="stylesheet" href="{% static "css/user_detail_style.css" %}">
{% endblock %}

{% block title %}{{ user.username }}{% endblock %}
{% block content %}
    <section id="user">
        <div class="container">
            <div class="user-profile">
                {% if user.profile.image %}
                  <img src="{{ user.profile.image_url }}" alt="person" width="150" height="150">
                {% endif %}
                <div class="user-description">
                    <h1>{{ user.username }}</h1>
                    <h4>{{ user.profile.location }}</h4>
                    <h5>Posts: {{ user.profile.get_posts_count }}</h5>
                    <p>{{ user.profile.bio }}</p>
                </div>
            </div>
        </div>
    </section>

    <section id="user-posts">
        <div class="container">
            <div class="posts">
                {% for post in posts %}
                    <a href="{{ post.get_absolute_url }}">
                          <img src="{{ post.image_url }}" width="300" height="300" alt="image">
                    </a>
                {% empty %}
                    <h2>0 posts :(</h2>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}

TripApp/users/templates/users/users_list.html
{% extends "posts/base.html" %}
{% load static %}
{% block stylesheet %}
    <link rel="stylesheet" href="{% static "css/user_list_style.css" %}">
{% endblock %}

{% block title %}User List{% endblock %}
{% block content %}
    <section id="people">
        <div class="container">
            {% for user in users %}
            <div class="person">
                <a href="{{ user.profile.get_absolute_url }}">
                    {% if user.profile.image %}
                    <img src="{{ user.profile.image_url }}" alt="person" width="100" height="100">
                    {% endif %}
                </a>
                <div class="person-info">
                    <h2><a href="{{ user.profile.get_absolute_url }}">{{ user.username }}</a></h2>
                    <h5>{{ user.profile.location}}</h5>
                </div>
                <div class="person-stats">
                    <h5>{{ user.profile.get_posts_count }} Post{{ user.profile.get_posts_count|pluralize }}</h5>
                    <h5>{{ user.profile.get_total_likes_count }} Likes{{ user.profile.get_total_likes_count|pluralize}}</h5>
                </div>
            </div>
            {% endfor %}
            <section id="paginator">
                {% include "posts/pagination.html" with page=users %}
            </section>
        </div>

    </section>
{% endblock %}