TripApp/TripApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('users/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

TripApp/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.home, name='home'),
    path('posts/', views.posts_list, name='posts_list'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/create/', views.create_post, name='create_post'),
    path('posts/<int:post_id>/update/', views.update_post, name='update_post'),
    path('posts/<int:post_id>/delete/', views.delete_post, name='delete_post'),
    path('posts/tags/<slug:slug>/', views.tagged_posts, name='tagged_posts'),
    path('posts/tags/', views.popular_tag_list, name='tag_list'),
    path('like/<int:post_id>/', views.post_like, name='post_like'),
    path('posts/comments/<int:comment_id>/update/', views.update_comment, name='update_comment'),
    path('posts/comments/<int:comment_id>/delete/', views.delete_comment, name='delete_comment'),
    path('posts/locations/', views.popular_location_list, name='location_list'),
]

TripApp/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('list/', views.users_list, name='users_list'),
    path('detail/<int:user_id>/', views.user_detail, name='user_detail'),
    path('edit/<int:user_id>', views.edit_profile, name='edit_user'),
    path('delete/<int:user_id>/', views.delete_profile, name='delete_user'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
]

TripApp/posts/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.conf import settings

from taggit.managers import TaggableManager

from PIL import Image

from .managers import PostManager, CommentManager


class Post(models.Model):
    name = models.CharField(max_length=100)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                             related_name='posts')
    about = models.TextField()
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='post_images/%Y/%m/%d/', null=True, blank=True)
    tags = TaggableManager()
    location = models.CharField(max_length=100)
    active = models.BooleanField(default=True)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                   related_name='posts_likes')
    # Default Manager
    objects = models.Manager()
    # Custom Manager
    posts = PostManager()

    def __str__(self):
        return f'{self.name}-{self.user.username}-{self.created}'

    @property
    def image_url(self):
        if self.image:
            return self.image.url
        return '#'

    @property
    def get_like_url(self):
        return reverse('posts:post_like', args=[self.pk])

    @property
    def get_absolute_url(self):
        return reverse('posts:post_detail', args=[self.pk])

    @property
    def get_likes_count(self):
        return self.likes.count()

    @property
    def tags_to_str(self):
        tags = [tag.name for tag in self.tags.all()]
        return ', '.join(tags)

    def save(self, *args, **kwargs):
        """ Resizing an image """
        super(Post, self).save(*args, **kwargs)

        if self.image:
            img = Image.open(self.image.path)

            if img.height > 500 or img.width > 500:
                output_size = (500, 500)
                img.thumbnail(output_size)
                img.save(self.image.path)

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.SET_NULL)
    body = models.TextField()
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)

    # Default Manager
    objects = models.Manager()
    # Custom Manager
    comments = CommentManager()

    def __str__(self):
        return f'{str(self.post)} commented by {self.user.username}'

    class Meta:
        verbose_name = 'comment'
        verbose_name_plural = 'comments'

TripApp/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('name', 'about', 'image', 'tags', 'location')

    def clean_location(self):
        location = self.cleaned_data['location']
        location = location.strip().title()
        return location


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)



TripApp/posts/views.py
from .models import Post, Comment
from .forms import CommentForm, PostForm

from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages
from django.db.models import Count

from taggit.models import Tag


def home(request):
    if request.user.is_authenticated:
        return redirect('posts:posts_list')
    return render(request, 'posts/home.html')


@login_required
def posts_list(request):
    posts_list = Post.posts.actives()
    paginator = Paginator(posts_list, 5)
    page = request.GET.get('page')
    posts = None

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request, 'posts/posts_list.html', {'page': page, 'posts': posts})


@login_required
def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    comments = Comment.objects.filter(post__id=post_id)
    new_comment = None

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            # Assign the current post to comment
            new_comment.post = post
            # Assign the current user to comment
            new_comment.user = request.user
            new_comment.save()
            messages.success(request, f'Your comment has been added!')
    else:
        comment_form = CommentForm()
    return render(request, 'posts/post_detail.html', {'post': post, 'comments': comments, 'comment_form': comment_form,
                                                      'new_comment': new_comment})


@login_required
def create_post(request):
    if request.method == 'POST':
        post_form = PostForm(data=request.POST, files=request.FILES)
        if post_form.is_valid():
            new_post = post_form.save(commit=False)
            new_post.user = request.user
            new_post.save()
            # saving tags
            post_form.save_m2m()
            messages.success(request, 'New post successfully created')
            return redirect(new_post.get_absolute_url)
    else:
        post_form = PostForm()
    return render(request, 'posts/post_create.html', {'post_form': post_form})


@login_required
def update_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.user:
        raise PermissionDenied
    else:
        if request.method == 'POST':
            post_form = PostForm(data=request.POST, files=request.FILES,
                                 instance=post)
            if post_form.is_valid():
                post_form.save()
                messages.success(request, 'Your post has been updated')
                return redirect(post.get_absolute_url)
        else:
            post_form = PostForm(instance=post)

        return render(request, 'posts/post_update.html', {'post_form': post_form, 'post': post})


@login_required
def delete_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.user:
        raise PermissionDenied
    else:
        if request.method == 'POST':
            post.delete()
            messages.success(request, 'Your post has been deleted')
            return redirect('posts:posts_list')
        return render(request, 'posts/post_delete_confirm.html', {'post': post})


@login_required
def tagged_posts(request, slug):
    tag = get_object_or_404(Tag, slug=slug)
    posts_list = Post.objects.filter(tags__in=[tag]).order_by('-created')
    paginator = Paginator(posts_list, 5)
    page = request.GET.get('page')
    posts = None

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request, 'posts/posts_list.html', {'posts': posts, 'page': page, 'tag': tag})


@login_required
def post_like(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    user = request.user
    if user in post.likes.all():
        post.likes.remove(user)
    else:
        post.likes.add(user)
    return redirect(post.get_absolute_url)


@login_required
def update_comment(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.user:
        raise PermissionDenied
    else:
        if request.method == 'POST':
            comment_form = CommentForm(data=request.POST, instance=comment)
            if comment_form.is_valid():
                comment_form.save()
                messages.success(request, 'Your comment has been updated')
                return redirect(reverse('posts:post_detail', args=[comment.post.pk]))
        else:
            comment_form = CommentForm(instance=comment)
        return render(request, 'posts/comment_update.html', {'comment_form': comment_form, 'comment': comment})


@login_required
def delete_comment(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    post = get_object_or_404(Post, pk=comment.post.pk)
    if request.user != comment.user:
        raise PermissionDenied
    else:
        if request.method == 'POST':
            comment.delete()
            messages.success(request, 'Your comment has been deleted')
            return redirect(reverse('posts:post_detail', args=[comment.post.pk]))
        return render(request, 'posts/comment_delete_confirm.html', {'post': post})


@login_required
def popular_tag_list(request):
    tags = Post.tags.most_common()[:10]
    return render(request, 'posts/popular_tag_list.html', {'tags': tags})


@login_required
def popular_location_list(request):
    locations = Post.objects.values('location').annotate(my_count=Count('location')).order_by('-my_count')[:10]
    return render(request, 'posts/popular_location_list.html', {'locations': locations})

TripApp/posts/templates/posts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/post_list_style.css' %}">
    {% block stylesheet %}
    {% endblock %}
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/9fada548c3.js" crossorigin="anonymous"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <nav id="navbar">
        <h1 class="logo">
            <a href="{% url "posts:posts_list" %}"><i class="fas fa-camera-retro fa-2x"></i><span class="logo-text">Trip</span>App</a>
        </h1>
        <ul>
            <li><a class="current" href="{% url "posts:posts_list" %}">Posts</a></li>
            <li><a href="{% url "users:users_list" %}">People</a></li>
            <li><a href="{% url "posts:tag_list" %}">Tags</a></li>
            <li><a href="{% url "posts:location_list" %}">Places</a></li>
            <li><a href="{% url "posts:create_post" %}">Create Post</a></li>
            <li><a href="{% url "users:user_detail" request.user.pk %}">My Posts</a></li>
            <li><a href="{% url "users:edit_user" request.user.pk %}">Profile</a></li>
            <li><a href="{% url "users:logout" %}"><i class="fas fa-sign-out-alt fa-1x"></i>Logout</a></li>
        </ul>
    </nav>

    {% block content %}
    {% endblock %}

    <footer>
        <p>TripApp &copy; 2020, All Rights Reserved</p>
    </footer>

    <script src="{% static "js/main.js" %}"></script>
</body>
</html>

TripApp/posts/templates/posts/comment_delete_confirm.html
{% extends "posts/base.html" %}
{% load static %}
{% block stylesheet %}
    <link rel="stylesheet" href="{% static "css/post_delete_confirm_style.css" %}">
{% endblock %}

{% block title %}Delete Comment{% endblock %}

{% block content %}
    <section id="delete-post">
        <div class="container">
            <h1>Are you sure you want delete this comment?</h1>
            <div id="delete-form">
                <form method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn">Yes</button>
                    <a href="{% url "posts:post_detail" post.pk %}" class="btn">No</a>
                </form>
            </div>
        </div>
    </section>
{% endblock %}

TripApp/posts/templates/posts/comment_update.html
{% extends "posts/base.html" %}
{% load static %}
{% block stylesheet %}
    <link rel="stylesheet" href="{% static "css/comment_update_style.css" %}">
{% endblock %}

{% block title %}Update Comment{% endblock %}

{% block content %}
    <section id="comment-update">
        <div class="container">
            <div id="update-form">
                <form method="post">
                    {% csrf_token %}
                    <textarea name="body" required id="id_body">{{ comment.body }}</textarea>
                    <div class="button">
                        <button type="submit" >Save</button>
                    </div>
                </form>
            </div>
        </div>
    </section>
{% endblock %}

TripApp/posts/templates/posts/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static "css/home_styles.css" %}" rel="stylesheet">
    <script src="https://kit.fontawesome.com/9fada548c3.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Comic+Neue&display=swap" rel="stylesheet">
    <title>TripApp</title>
</head>
<body>
    <header>
        <nav id="navbar">
            <div class="container">
                <h1 class="logo"><a href="{% url "posts:home" %}"><i class="fas fa-camera-retro fa-2x"></i><span class="logo-text">Trip</span>App</a></h1>
                <ul>
                    <li><a href="{% url "users:login" %}"><i class="fas fa-sign-in-alt fa-2x"></i>Sign In</a></li>
                    <li><a href="{% url "users:register" %}"><i class="fas fa-user-plus fa-2x"></i>Sign Up</a></li>
                </ul>
            </div>
        </nav>
    </header>

    <main>
        <section id="photos">
            <div class="container">
                <div class="box box-1">
                    <h1>Travel Around The World</h1>
                    <img src="{% static "img/adventure-backlit-dawn-dusk-207896.jpg" %}" alt="image">
                </div>
                <div class="box box-2">
                    <h1>Share Photos With Friends</h1>
                    <img src="{% static "img/person-using-laptop-computer-during-daytime-196655.jpg" %}" alt="image">
                </div>
            </div>
        </section>
        <section id="join-us">
                <a href="{% url "users:register" %}">Join Us</a>
        </section>
    </main>

    <footer>
        <p>TripApp &copy; 2020, All Rights Reserved</p>
    </footer>

</body>
</html>

TripApp/posts/templates/posts/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <span class="previous">
                <a href="?page={{ page.previous_page_number }}">Previous</a>
            </span>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
            <span class="next">
                <a href="?page={{ page.next_page_number }}">Next</a>
            </span>
        {% endif %}
    </span>
</div>

TripApp/posts/templates/posts/popular_location_list.html
{% extends "posts/base.html" %}
{% load static %}
{% block stylesheet %}
    <link rel="stylesheet" href="{% static "css/tag_list_style.css" %}">
{% endblock %}

{% block title %}Location List{% endblock %}

{% block content %}
    <section id="tags">
        <div class="container">
            <ol>
                {% for location in locations %}
                <li><a> {{ location.location }}</a></li>
                {% endfor %}
            </ol>
        </div>
    </section>
{% endblock %}


TripApp/posts/templates/posts/popular_tag_list.html
{% extends "posts/base.html" %}
{% load static %}
{% block stylesheet %}
    <link rel="stylesheet" href="{% static "css/tag_list_style.css" %}">
{% endblock %}

{% block title %}Tag List{% endblock %}

{% block content %}
    <section id="tags">
        <div class="container">
            <ol>
                {% for tag in tags %}
                    <li><a href="{% url "posts:tagged_posts" tag.slug %}"> #{{ tag.name }}</a></li>
                {% endfor %}
            </ol>
        </div>
    </section>
{% endblock %}


TripApp/posts/templates/posts/post_create.html
{% extends "posts/base.html" %}
{% load static %}
{% block stylesheet %}
    <link rel="stylesheet" href="{% static "css/post_create_style.css" %}">
{% endblock %}

{% block title %}Create Post{% endblock %}

{% block content %}
    <div class="container">
        <form id="post-form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_name">Name</label>
                <input type="text" name="name" required id="id_name">
            </div>
            <div class="form-group">
                <label for="id_about">About</label>
                <textarea name="about" required id="id_about"></textarea>
            </div>
            <div class="form-group">
                <label for="id_tags">Tags (comma separated)</label>
                <input type="text" data-role="tagsinput" name="tags" required id="id_tags">
            </div>
            <div class="form-group">
                <label for="id_location">Location</label>
                <input type="text" name="location" maxlength="100" id="id_location">
            </div>
            <div class="form-group">
                <label for="id_image">Image</label>
                <input type="file" name="image" accept="image/*" required id="id_image">
            </div>
            <button type="submit">Add Post</button>
        </form>
    </div>
{% endblock %}




TripApp/posts/templates/posts/post_delete_confirm.html
{% extends "posts/base.html" %}
{% load static %}
{% block stylesheet %}
    <link rel="stylesheet" href="{% static "css/post_delete_confirm_style.css" %}">
{% endblock %}

{% block title %}Confirm Delete{% endblock %}

{% block content %}
    <section id="delete-post">
        <div class="container">
            <h1>Are you sure you want delete this post?</h1>
            <div id="delete-form">
                <form method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn">Yes</button>
                    <a href="{% url "posts:post_detail" post.pk %}" class="btn">No</a>
                </form>
            </div>
        </div>
    </section>
{% endblock %}

TripApp/posts/templates/posts/post_detail.html
{% extends "posts/base.html" %}
{% load static %}
{% block stylesheet %}
    <link rel="stylesheet" href="{% static "css/post_detail_style.css" %}">
{% endblock %}

{% block title %}{{ post.name }}{% endblock %}

{% block content %}
    <section id="post">
        <div class="container">
            <div class="post">
                <div class="post-info">
                    <div class="user-info">
                        <div class="info">
                            <img src="{{ user.profile.image_url }}" alt="user-image" width="60" height="60">
                            <h2>{{ user.username }}</h2>
                        </div>
                        <div class="icons">
                            {% if request.user == post.user %}
                                <a href="{% url "posts:delete_post" post.pk %}"><i class="fas fa-trash-alt fa-2x"></i></a>
                                <a href="{% url "posts:update_post" post.pk %}"><i class="fas fa-edit fa-2x"></i></a>
                            {% endif %}
                        </div>
                    </div>
                    <h2><a href="{{ post.get_absolute_url }}">{{ post.name }}</a></h2>
                    <h5>{{ post.location }}</h5>
                    <h5>{{ post.created|date:"j M Y" }}</h5>
                    <p>{{ post.about }}</p>
                </div>
               <img id="post-image" src="{{ post.image_url }}" alt="image">
                <div class="post-info">
                {% if request.user not in post.likes.all %}
                    <a href="{{ post.get_like_url }}"><i class="fas fa-thumbs-up fa-2x"></i></a>
                {% else %}
                    <a href="{{ post.get_like_url }}"><i class="fas fa-thumbs-down fa-2x"></i></a>
                {% endif %}
                    <span class="likes">
                        <h5><span class="likes-number">{{ post.get_likes_count }}</span> Like{{ post.get_likes_count|pluralize }}
                        </h5></span>
                    <div class="taggs">
                        <ul>
                            {% for tag in post.tags.all %}
                                <li><span class="tag"><a href="{% url "posts:tagged_posts" tag.slug %}">
                                    {{ tag.name }}</a></span></li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="comments">
                        {% for comment in post.comments.all %}
                            {% if request.user == comment.user %}
                                <div class="comment comment-flex">
                                    <div class="comment-content">
                                        <a href="{% url "users:user_detail" comment.user.pk %}">{{ comment.user.username }}</a>
                                        <p>{{ comment.body }}</p>
                                    </div>
                                    <div class="icons">
                                        <a href="{% url "posts:delete_comment" comment.pk %}"><i class="fas fa-trash-alt fa-1x"></i></a>
                                        <a href="{% url "posts:update_comment" comment.pk %}"><i class="fas fa-edit fa-1x"></i></a>
                                    </div>
                                </div>
                            {% else  %}
                                <div class="comment">
                                    <a href="{% url "users:user_detail" comment.user.pk %}">{{  comment.user.username}}</a>
                                    <p>{{ comment.body }}</p>
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                    <form id="comment-form" method="post">
                        {% csrf_token %}
                        <textarea name="body" required id="id_body"></textarea>
                        <button type="submit" class="btn">Add Comment</button>
                    </form>
                </div>
            </div>
        </section>
{% endblock %}





TripApp/posts/templates/posts/post_update.html
{% extends "posts/base.html" %}
{% load static %}
{% block stylesheet %}
    <link rel="stylesheet" href="{% static "css/post_create_style.css" %}">
{% endblock %}

{% block title %}Update Post{% endblock %}

{% block content %}
    <div class="container">
        <form id="post-form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_name">Name</label>
                <input type="text" name="name" required id="id_name" value="{{ post.name }}">
            </div>
            <div class="form-group">
                <label for="id_about">About</label>
                <textarea name="about" required id="id_about">{{ post.about }}</textarea>
            </div>
            <div class="form-group">
                <label for="id_tags">Tags (comma separated)</label>
                <input type="text" data-role="tagsinput" name="tags" required id="id_tags" value="{{ post.tags_to_str }}">
            </div>
            <div class="form-group">
                <label for="id_location">Location</label>
                <input type="text" name="location" maxlength="100" id="id_location" value="{{ post.location }}">
            </div>
            <button type="submit">Save</button>
        </form>
    </div>
{% endblock %}

TripApp/posts/templates/posts/posts_list.html
{% extends "posts/base.html" %}
{% load static %}
{% block stylesheet %}
    <link rel="stylesheet" href="{% static "css/post_list_style.css" %}">
    <link rel="stylesheet" href="{% static "css/pagination_style.css" %}">
{% endblock %}

{% block title %}Posts List{% endblock %}

{% block content %}
        <section id="posts">
        <div class="container">
            {% for post in posts %}
                <div class="post">
                    <div class="post-info">
                        <div class="user-info">
                            <a href="{{ post.user.profile.get_absolute_url }}">
                                <div style="display: flex">
                                    <img src="{{ post.user.profile.image_url }}" alt="user-image" width="60" height="60">
                                    <h2>{{ post.user.username}}</h2>
                                </div>
                            </a>
                        </div>
                        <h2><a href="{{ post.get_absolute_url }}">{{ post.name }}</a></h2>
                        <h5>{{ post.location }}</h5>
                        <h5>{{ post.created|date:"j M Y" }}</h5>
                        <p>{{ post.about }}</p>
                    </div>
                    {% if post.image %}
                    <img id="post-image" src="{{ post.image_url }}" alt="image">
                    {% endif %}
                    <div class="post-info">
                        <span class="likes"><h5><span class="likes-number">{{ post.get_likes_count }}</span> Like
                        {{ post.get_likes_count|pluralize }}</h5></span>
                        <div class="taggs">
                            <ul>
                                {% for tag in post.tags.all %}
                                    <span class="tag"><li><a href="{% url "posts:tagged_posts" tag.slug %}">
                                        {{ tag.name }}</a></li></span>
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="comments">
                            {% for comment in post.comments.all|slice:":3" %}
                                <div class="comment">
                                    <a href="{{ comment.user.profile.get_absolute_url }}">
                                        {{ comment.user.username }}</a>
                                    <p>{{ comment.body }}</p>
                                </div>
                            {% endfor %}
                        </div>
                        <a class="btn" href="{{ post.get_absolute_url }}">Add Comment</a>
                    </div>
                </div>
        {% endfor %}
        <section id="paginator">
        	{% include "posts/pagination.html" with page=posts %}
        </section>
    </section>

{% endblock %}
